spring.data.mongodb.uri=${DB_URL}

server.servlet.context-path=/api/v1.0

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=prometheus
server.port=9090
clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${JWKS_URL}
clerk.webhook.secret=${WEB_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}